Repository agiledev-students-spring-2023/final-project-openedu, pull requests merged in 2023-03, with the labels that each got.

#24 Folders structure added & MUI installed & react-dom installed & boilerplate added (Todo)
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/App.test.js
  front-end/src/MainRouter.jsx
  front-end/src/containers/Layout/index.jsx
  front-end/src/containers/readme.txt
  front-end/src/index.js
  front-end/src/logo.svg
  front-end/src/pages/Courses/index.jsx
  front-end/src/pages/Index/index.jsx
  front-end/src/pages/Login/index.jsx
  front-end/src/pages/Subjects/index.jsx
  front-end/src/pages/readme.txt
  front-end/src/reportWebVitals.js
  front-end/src/setupTests.js
Labels: spike

#33 chore:axios dependency added; mockaroo api added; picsum url added
  front-end/mockApi/apis.js
  front-end/mockApi/readme.txt
  front-end/mockApi/test.js
  front-end/package.json
Labels: spike

#38 Add navbar
  README.md
  front-end/package.json
  front-end/src/containers/BottomNavBar/index.jsx
  front-end/src/containers/Layout/index.jsx
Labels: task

#41 User Story/11/create basic login and signup pages
  front-end/src/MainRouter.jsx
  front-end/src/containers/LoginComponent/index.jsx
  front-end/src/containers/SignupComponent/index.jsx
  front-end/src/pages/Password/index.jsx
  front-end/src/pages/Signup/index.jsx
  package.json
Labels: task

#43 feat:change the basic layout of the begin page; add a front cover.
  front-end/src/containers/BeginComponent/index.jsx
  front-end/src/pages/Index/index.jsx
  front-end/src/pages/Login/index.jsx
Labels: task

#44 feat: change buttons and textfields on signup page and password page
  front-end/src/containers/BeginComponent/index.jsx
  front-end/src/containers/LoginComponent/index.jsx
  front-end/src/containers/SignupComponent/index.jsx
  front-end/src/pages/Password/index.jsx
  front-end/src/pages/Signup/index.jsx
  front-end/src/pages/Subjects/index-Recents.jsx
  front-end/src/pages/courses/CommentCard.jsx
  front-end/src/pages/courses/CourseDetail.jsx
  front-end/src/pages/courses/CourseList.jsx
  front-end/src/pages/courses/CourseListCard.jsx
Labels: task

#45 feat: change layout and styling of password page
  front-end/src/containers/BeginComponent/index.jsx
  front-end/src/containers/LoginComponent/index.jsx
  front-end/src/containers/SignupComponent/index.jsx
Labels: task

#46 User story/10/task/34/begin page basic functions
  front-end/src/containers/BackButton/index.jsx
  front-end/src/containers/BeginComponent/index.jsx
  front-end/src/pages/Index/index.jsx
  front-end/src/pages/Login/index.jsx
Labels: task

#52 Landing combined, user profile edible, used avatar implemented
  front-end/mockApi/apis.mjs
  front-end/mockApi/test.mjs
  front-end/package.json
  front-end/public/logo.png
  front-end/src/App.jsx
  front-end/src/MainRouter.jsx
  front-end/src/containers/BackButton/BackButton.jsx
  front-end/src/containers/BackgroundImage/index.jsx
  front-end/src/containers/Layout/Layout.jsx
  front-end/src/containers/StyledAvatar/index.jsx
  front-end/src/img/logo.png
  front-end/src/pages/home/Home.jsx
  front-end/src/pages/landing/LandingPage.jsx
  front-end/src/pages/landing/LandingUI.jsx
  front-end/src/pages/landing/begin/Begin.jsx
  front-end/src/pages/landing/begin/BeginComponent.jsx
  front-end/src/pages/landing/signin/SignIn.jsx
  front-end/src/pages/landing/signin/SignInComponent.jsx
  front-end/src/pages/landing/signup/SignUp.jsx
  front-end/src/pages/landing/signup/SignUpComponent.jsx
  front-end/src/pages/subjects/SuggestSubjectList.jsx
  front-end/src/pages/userprofile/EditProfile.jsx
  front-end/src/pages/userprofile/RecentlyUsedAvatars.jsx
  front-end/src/util/Util.mjs
Labels: task, spike

#53 Subject component finished
  front-end/src/MainRouter.jsx
  front-end/src/pages/landing/LandingUI.jsx
  front-end/src/pages/subjects/CourseCard.jsx
  front-end/src/pages/subjects/RecentSubjectList.jsx
  front-end/src/pages/subjects/SubjectCard.jsx
  front-end/src/pages/subjects/SuggestSubjectList.jsx
Labels: user story, task

#56 <feat>: add typewriter effect to subjectdetail page
  front-end/package.json
  front-end/src/pages/subjects/SubjectDetail.jsx
Labels: enhancement, task

#58 User profile
  front-end/package.json
  front-end/src/MainRouter.jsx
  front-end/src/containers/Layout/Layout.jsx
  front-end/src/containers/PostCard/PostCard.jsx
  front-end/src/pages/home/Home.jsx
  front-end/src/pages/landing/LandingUi.jsx
  front-end/src/pages/posts/ComposePost.jsx
  front-end/src/pages/posts/ViewPost.jsx
  front-end/src/pages/userprofile/EditProfile.jsx
  front-end/src/pages/userprofile/RecentlyUsedAvatars.jsx
  front-end/src/pages/userprofile/UserProfile.jsx
  front-end/src/pages/video/PlayScreen.jsx
Labels: task

#59 style: typewriter effect enhancement on SubjectDetail.jsx
  front-end/package.json
  front-end/src/pages/subjects/SubjectDetail.jsx
  front-end/src/pages/subjects/SubjectList.jsx
Labels: enhancement

#60 Router rework
  front-end/public/index.html
  front-end/src/App.jsx
  front-end/src/MainRouter.jsx
  front-end/src/containers/BackButton/BackButton.jsx
  front-end/src/containers/BottomNavBar/BottomNavBar.jsx
  front-end/src/containers/Layout/Layout.jsx
  front-end/src/index.jsx
  front-end/src/pages/course/CourseList.jsx
  front-end/src/pages/home/Home.jsx
  front-end/src/pages/landing/Landing.jsx
  front-end/src/pages/landing/LandingPage.jsx
  front-end/src/pages/landing/LoginWizard.jsx
  front-end/src/pages/subjects/CourseCard.jsx
  front-end/src/pages/subjects/SubjectCard.jsx
  front-end/src/pages/subjects/SubjectDetail.jsx
  front-end/src/pages/subjects/SubjectList.jsx
  front-end/src/pages/userprofile/EditProfile.jsx
  front-end/src/pages/userprofile/RecentlyUsedAvatars.jsx
  front-end/src/pages/userprofile/UserProfile.jsx
  front-end/src/util/Logger.mjs
  front-end/src/util/Routing.mjs
  front-end/src/util/Util.mjs
Labels: enhancement, task, spike
