Repository agiledev-students-spring-2023/final-project-openedu, pull requests merged in 2023-04, with the labels that each got.

#68 feat: SubjectDetail display img, progressbar rework
  .gitignore
  front-end/public/logo 2.png
  front-end/src/pages/course/CourseDetail.jsx
  front-end/src/pages/subjects/CourseCard.jsx
  front-end/src/pages/subjects/SubjectDetail.jsx
  front-end/src/pages/subjects/SubjectList.jsx
  package.json
Labels: task

#67 Themeing
  front-end/.eslintrc.cjs
  front-end/package.json
  front-end/src/containers/BackgroundImage/index.jsx
  front-end/src/containers/BottomNavBar/BottomNavBar.jsx
  front-end/src/pages/home/Home.jsx
  front-end/src/pages/userprofile/EditProfile.jsx
  front-end/src/pages/userprofile/RecentlyUsedAvatars.jsx
  front-end/src/pages/userprofile/UserProfile.jsx
  front-end/src/util/Util.mjs
Labels: task, spike

#69 merge: Backend Mock APIs
  back-end/.eslintrc.cjs
  back-end/package.json
  back-end/src/networking/NetworkCore.mjs
  back-end/src/util/MockData.mjs
  back-end/src/util/Util.mjs
  front-end/.eslintrc.cjs
Labels: task, spike

#70 feat: SubjectCard completion rate linear progress bar
  front-end/src/pages/subjects/RecentSubjectList.jsx
  front-end/src/pages/subjects/SubjectCard.jsx
  front-end/src/pages/subjects/SubjectList.jsx
  front-end/src/pages/subjects/SuggestSubjectList.jsx
Labels: task

#76 User story/22/task/73/browse blogs
  back-end/src/networking/NetworkCore.mjs
  back-end/src/util/MockData.mjs
  front-end/src/containers/PostCard/PostCard.jsx
  front-end/src/pages/posts/ViewPost.jsx
  front-end/src/pages/userprofile/UserProfile.jsx
  front-end/src/util/Routing.mjs
Labels: task

#79 Test mock data
  back-end/package.json
  back-end/src/util/MockData.mjs
  back-end/tests/test_mock_data.mjs
  package.json
Labels: spike

#80 Spike/77/fetching blog post data from back end
  back-end/package.json
  back-end/src/networking/NetworkCore.mjs
  back-end/src/util/MockData.mjs
  front-end/src/containers/PostCard/PostCard.jsx
  front-end/src/pages/posts/ViewPost.jsx
  front-end/src/pages/userprofile/UserProfile.jsx
  package.json
Labels: spike

#84 [WIP] Style: Homepage UI redesign
  front-end/src/App.jsx
  front-end/src/pages/home/Home.jsx
  front-end/src/pages/subjects/SubjectList.jsx
  front-end/src/util/Util.mjs
Labels: task

#83 chore:get background image from backend
  back-end/src/networking/NetworkCore.mjs
  back-end/src/util/MockData.mjs
  front-end/src/containers/BackgroundImage/index.jsx
Labels: task

#85 feature: add feedback page
  back-end/package.json
  front-end/package.json
  front-end/src/MainRouter.jsx
  front-end/src/containers/FeedbackCard/FeedbackCard.jsx
  front-end/src/pages/feedback/Feedback.jsx
  front-end/src/pages/userprofile/UserProfile.jsx
  front-end/src/util/Routing.mjs
  package.json
Labels: task

#86 feat: complete feedback popup form
  front-end/src/containers/FeedbackCard/FeedbackCard.jsx
  front-end/src/pages/feedback/Feedback.jsx
  front-end/src/pages/feedback/Form.jsx
  front-end/src/pages/userprofile/UserProfile.jsx
  front-end/src/util/Routing.mjs
Labels: task

#87 Task/81/post page UI refine
  front-end/src/containers/PostCard/PostCard.jsx
  front-end/src/pages/posts/ViewPost.jsx
Labels: task

#88 feat: checkbox on feedback form
  front-end/src/pages/feedback/Feedback.jsx
  front-end/src/pages/feedback/Form.jsx
Labels: task

#89 Feat: SubjectCard & CourseCard Img now pulling from backend.
  front-end/package.json
  front-end/src/containers/CourseCard/CourseCardAtHome.jsx
  front-end/src/pages/home/Home.jsx
  front-end/src/pages/subjects/CourseCard.jsx
  front-end/src/pages/subjects/SubjectCard.jsx
  front-end/src/pages/subjects/SubjectDetail.jsx
Labels: task

#90 Feature: feedback form from backend
  back-end/src/util/MockData.mjs
  front-end/src/containers/FeedbackCard/FeedbackCard.jsx
  front-end/src/pages/feedback/Feedback.jsx
  front-end/src/pages/posts/ViewPost.jsx
Labels: task

#93 Spike/91/retrive images from backend
  front-end/src/containers/CourseCard/CourseCardAtHome.jsx
  front-end/src/containers/FeedbackCard/FeedbackCard.jsx
  front-end/src/containers/PostCard/PostCard.jsx
  front-end/src/pages/course/CourseDetail.jsx
  front-end/src/pages/lectures/LecturePlay.jsx
  front-end/src/pages/subjects/CourseCard.jsx
  front-end/src/pages/subjects/SubjectCard.jsx
Labels: spike

#95 Homepage UI redesign
  back-end/src/networking/NetworkCore.mjs
  back-end/src/util/MockData.mjs
  front-end/src/containers/CourseCard/CourseCardAtHome.jsx
  front-end/src/pages/home/Home.jsx
  front-end/src/pages/subjects/CourseCard.jsx
  front-end/src/pages/subjects/SubjectDetail.jsx
  front-end/src/util/Util.mjs
Labels: bug, enhancement, task

#96 test: recentCourse & suggestedCourse unit test
  back-end/src/util/MockData.mjs
  back-end/tests/test_mock_data.mjs
  back-end/tests/test_recentCourse_mockData.mjs
  back-end/tests/test_suggestCourse_mockData.mjs
  package.json
Labels: task

#103 Viewpostcolor
  front-end/src/containers/CourseCard/CourseCardAtHome.jsx
  front-end/src/pages/posts/ViewPost.jsx
Labels: task

#107 chore:pull avatar img from backend in edit-profile and recently-used-…
  front-end/src/pages/userprofile/EditProfile.jsx
  front-end/src/pages/userprofile/RecentlyUsedAvatars.jsx
Labels: task

#109 feat: add localStorage serialization for key
  front-end/src/pages/landing/LoginWizard.jsx
  front-end/src/util/LocalStorage.mjs
  front-end/src/util/Util.mjs
Labels: task

#110 Homepage UI tweek
  front-end/src/containers/CourseCard/CourseCardAtHome.jsx
  front-end/src/pages/home/Home.jsx
  front-end/src/util/LocalStorage.mjs
Labels: task, in progress

#112 Homepage UI redesign
  front-end/src/containers/CourseCard/CourseCardAtHome.jsx
  front-end/src/pages/home/Home.jsx
Labels: task, in progress

#113 Homepage UI redesign
  back-end/package.json
  front-end/src/MainRouter.jsx
  front-end/src/containers/CourseCard/CourseCardAtHome.jsx
  front-end/src/pages/home/Home.jsx
Labels: task

#114 fix: SuggestSubjectList axios status 0 error
  back-end/.babelrc
  back-end/.eslintrc.cjs
  back-end/README.md
  back-end/package.json
  back-end/server/controllers/CourseController.mjs
  back-end/server/models/CourseModel.mjs
  back-end/server/routers/CourseRouter.mjs
  back-end/src/main.mjs
  back-end/src/networking/NetworkCore.mjs
  back-end/src/public/index.html
  back-end/src/util/Constants.mjs
  back-end/src/util/FmtTime.mjs
  back-end/src/util/Logger.mjs
  back-end/src/util/MockData.mjs
  back-end/src/util/ThridPartyAPIs.mjs
  back-end/src/util/Util.mjs
  back-end/tests/testMockData.test.js
  back-end/tests/test_backend.mjs
  front-end/src/pages/home/Home.jsx
  front-end/src/pages/subjects/RecentSubjectList.jsx
  front-end/src/pages/subjects/SuggestSubjectList.jsx
  package.json
Labels: spike

#111 merge: Token-based authentication system
  .github/workflows/back-end-ci.yml
  .github/workflows/front-end-ci.yml
  back-end/package.json
  back-end/server/controllers/CourseController.mjs
  back-end/src/main.mjs
  back-end/src/networking/NetworkCore.mjs
  back-end/src/networking/RestfulMgr.mjs
  back-end/src/networking/db/AtomicCounter.mjs
  back-end/src/networking/db/MongoMgr.mjs
  back-end/src/networking/db/MongoModels.mjs
  back-end/src/util/MockData.mjs
  back-end/src/util/ThridPartyAPIs.mjs
  back-end/src/util/Util.mjs
  back-end/tests/testMockData.test.js
  front-end/package.json
  front-end/src/mockApi/apis.mjs
  front-end/src/mockApi/readme.txt
  front-end/src/mockApi/test.mjs
  front-end/src/pages/userprofile/EditProfile.jsx
  front-end/src/pages/userprofile/RecentlyUsedAvatars.jsx
  front-end/src/pages/userprofile/UserProfile.jsx
  front-end/src/util/Util.mjs
  package.json
Labels: spike

#115 DB support in LoginWizard & UI Polishment
  back-end/src/networking/RestfulMgr.mjs
  back-end/src/networking/db/MongoMgr.mjs
  back-end/src/util/Util.mjs
  front-end/src/App.jsx
  front-end/src/containers/BackgroundImage/index.jsx
  front-end/src/containers/BottomNavBar/BottomNavBar.jsx
  front-end/src/containers/Layout/Layout.jsx
  front-end/src/pages/home/Home.jsx
  front-end/src/pages/landing/Landing.jsx
  front-end/src/pages/landing/LoginWizard.jsx
  front-end/src/pages/subjects/SubjectDetail.jsx
  front-end/src/pages/userprofile/EditProfile.jsx
  front-end/src/pages/userprofile/RecentlyUsedAvatars.jsx
  front-end/src/util/Util.mjs
Labels: user story, task

#116 Post to db basic
  back-end/src/networking/RestfulMgr.mjs
  back-end/src/networking/db/MongoMgr.mjs
  back-end/src/networking/db/MongoModels.mjs
  front-end/src/containers/PostCard/PostCard.jsx
  front-end/src/pages/posts/ComposePost.jsx
Labels: spike

#117 subject DB built
  back-end/src/networking/NetworkCore.mjs
  back-end/src/networking/RestfulMgr.mjs
  back-end/src/networking/db/MongoModels.mjs
Labels: task

#120 Subj course card styling
  back-end/src/networking/NetworkCore.mjs
  back-end/src/networking/RestfulMgr.mjs
  back-end/src/networking/db/MongoModels.mjs
  front-end/src/pages/subjects/CourseCard.jsx
  front-end/src/pages/subjects/SubjectCard.jsx
  front-end/src/pages/subjects/SubjectDetail.jsx
Labels: task

#121 Course db
  back-end/src/networking/RestfulMgr.mjs
  back-end/src/networking/db/MongoModels.mjs
  back-end/src/util/ThridPartyAPIs.mjs
  front-end/package.json
  front-end/src/pages/course/CourseDetail.jsx
  front-end/src/pages/lectures/LectureCardButton.jsx
  front-end/src/pages/lectures/LecturePlay.jsx
  front-end/src/pages/subjects/CourseCard.jsx
  front-end/src/util/Routing.mjs
  front-end/src/util/Util.mjs
Labels: task

#123 Spike/122/fix user post view
  back-end/src/networking/RestfulMgr.mjs
  back-end/src/networking/db/MongoMgr.mjs
  front-end/src/pages/posts/ViewPost.jsx
  front-end/src/pages/userprofile/UserProfile.jsx
Labels: spike

#125 Task/124/refine user post frontend
  back-end/src/networking/RestfulMgr.mjs
  front-end/src/pages/posts/ComposePost.jsx
  front-end/src/pages/userprofile/UserProfile.jsx
Labels: task

#126 Jwt integration
  back-end/package.json
  back-end/server/controllers/CourseController.mjs
  back-end/src/networking/RestfulMgr.mjs
  back-end/src/networking/db/MongoMgr.mjs
  back-end/src/networking/db/MongoModels.mjs
  back-end/src/util/MockData.mjs
  back-end/src/util/ThirdPartyAPIs.mjs
  back-end/src/util/Util.mjs
  front-end/src/pages/course/CourseDetail.jsx
  front-end/src/pages/feedback/Feedback.jsx
  front-end/src/pages/home/Home.jsx
  front-end/src/pages/lectures/LecturePlay.jsx
  front-end/src/pages/posts/ViewPost.jsx
  front-end/src/pages/subjects/RecentSubjectList.jsx
  front-end/src/pages/subjects/SubjectDetail.jsx
  front-end/src/pages/subjects/SubjectList.jsx
  front-end/src/pages/subjects/SuggestSubjectList.jsx
  front-end/src/pages/userprofile/EditProfile.jsx
  front-end/src/pages/userprofile/RecentlyUsedAvatars.jsx
  front-end/src/pages/userprofile/UserProfile.jsx
  front-end/src/util/Util.mjs
Labels: task, spike
